[dependencies]
base = "0.11.1"
serde = "2.3.0"
datetime = "0.1.3"
cert = "https://github.com/nomeata/ic-certification#v0.1.3@c403ffec0a60f658a1009976c785aa567ff0da77"
icrc1-mo = "0.0.15"
icrc2-mo = "0.0.13"
icrc3-mo = "0.2.4"
icrc4-mo = "0.0.5"
uuid = "1.0.0"

[dev-dependencies]
test = "1.2.0"
fuzz = "0.2.0"
matchers = "https://github.com/kritzcreek/motoko-matchers#v1.3.0@3dac8a071b69e4e651b25a7d9683fe831eb7cffd"